-- 25 Diverse Content Templates for Public Template Library
-- Additional templates to expand the library

-- 1. Fitness Instagram Caption
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Morning Workout Motivation', 'Energizing fitness caption for morning workout posts', '{"caption": "Rise and grind! 💪 \n\nThere''s no better way to start your day than with movement. Your future self will thank you for every drop of sweat.\n\nWhat''s your morning routine? Drop a 🌅 if you''re starting your fitness journey today!", "call_to_action": "Comment your workout", "emoji_suggestions": ["💪", "🌅", "🔥", "⚡"]}'::jsonb, 'social_media', 'fitness', 'instagram', 'inspirational', 'caption', true, ARRAY['fitness', 'motivation', 'morning', 'workout', 'health'], 'beginner', 5);

-- 2. Tech YouTube Video Description
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Tech Review Description', 'Professional YouTube description for tech reviews', '{"description": "In this video, I review the latest [PRODUCT NAME] and share my honest thoughts after [TIME PERIOD] of use.\n\n🎯 Key Features:\n• [FEATURE 1]\n• [FEATURE 2] \n• [FEATURE 3]\n\n💰 Pricing: [PRICE RANGE]\n📊 Overall Rating: [X]/10\n\n🔗 Links mentioned:\n[PRODUCT LINK]\n[ALTERNATIVE 1]\n[ALTERNATIVE 2]\n\n📱 Follow me on social media:\nInstagram: [@HANDLE]\nTwitter: [@HANDLE]\n\n⏰ Timestamps:\n00:00 - Introduction\n01:30 - Unboxing\n03:45 - Design & Build\n06:20 - Performance\n09:15 - Pros & Cons\n11:30 - Final Verdict", "seo_tags": ["tech review", "product review", "technology"], "affiliate_disclaimer": true}'::jsonb, 'content_creation', 'tech', 'youtube', 'professional', 'description', true, ARRAY['tech', 'review', 'youtube', 'description', 'seo'], 'intermediate', 15);

-- 3. Cooking TikTok Script
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Quick Recipe Tutorial', 'Fast-paced cooking tutorial for TikTok', '{"hook": "POV: You''re hungry but only have 5 minutes", "steps": ["Show ingredients", "Quick prep montage", "Cooking transformation", "Money shot final dish", "Taste test reaction"], "text_overlays": ["Day 47 of easy recipes", "Less than $5 per serving", "Ready in 5 min"], "music_suggestion": "upbeat trending audio", "hashtags": ["#quickrecipe", "#cookinghack", "#easy meals", "#budgetcooking"]}'::jsonb, 'content_creation', 'cooking', 'tiktok', 'casual', 'script', true, ARRAY['cooking', 'recipe', 'tiktok', 'quick', 'budget'], 'beginner', 10);

-- 4. Fashion Instagram Bio
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Fashion Influencer Bio', 'Stylish Instagram bio for fashion content creators', '{"bio": "✨ Style enthusiast | 📍[CITY]\n👗 Daily outfit inspo\n🛍️ Affordable fashion finds\n📧 [EMAIL] for collabs\n🌟 [AGE] | She/Her", "link_in_bio": "Latest haul 👇", "highlights": ["OOTD", "Hauls", "Try-On", "Tips"], "emoji_style": "minimal chic"}'::jsonb, 'branding', 'fashion', 'instagram', 'enthusiastic', 'bio', true, ARRAY['fashion', 'bio', 'instagram', 'style', 'influencer'], 'beginner', 3);

-- 5. Business LinkedIn Post
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Industry Insight Post', 'Professional LinkedIn post sharing industry insights', '{"caption": "I''ve been in [INDUSTRY] for [X] years, and I''ve noticed something interesting:\n\n[INDUSTRY TREND/INSIGHT]\n\nHere''s why this matters:\n\n🔍 [POINT 1]\n📊 [POINT 2] \n💡 [POINT 3]\n\nThe companies that [ACTION] will be the ones that [OUTCOME].\n\nWhat are your thoughts on this trend? I''d love to hear different perspectives.\n\n#[INDUSTRYHASHTAG] #Business #Leadership #Innovation", "call_to_action": "Share your experience", "engagement_prompt": "What trends are you seeing?"}'::jsonb, 'professional', 'business', 'linkedin', 'professional', 'caption', true, ARRAY['business', 'linkedin', 'professional', 'industry', 'thought-leadership'], 'intermediate', 20);

-- 6. Travel Blog Outline
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Travel Destination Guide', 'Comprehensive blog outline for travel guides', '{"title": "The Ultimate [DESTINATION] Travel Guide", "introduction": "Hook with personal story, why visit, best time to go", "sections": [{"heading": "Getting There", "subpoints": ["Transportation options", "Best airports", "Local transportation"]}, {"heading": "Where to Stay", "subpoints": ["Best neighborhoods", "Hotel recommendations", "Budget options"]}, {"heading": "Top Attractions", "subpoints": ["Must-see landmarks", "Hidden gems", "Free activities"]}, {"heading": "Local Food", "subpoints": ["Traditional dishes", "Best restaurants", "Street food spots"]}, {"heading": "Practical Tips", "subpoints": ["Safety advice", "Budget breakdown", "Cultural etiquette"]}], "conclusion": "Final thoughts, encourage comments, social sharing", "word_count_target": 2500, "seo_keywords": ["[destination] travel guide", "things to do in [destination]"]}'::jsonb, 'content_creation', 'travel', 'universal', 'educational', 'blog_outline', true, ARRAY['travel', 'blog', 'guide', 'destination', 'seo'], 'intermediate', 30);

-- 7. Entertainment Twitter Thread
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Movie Review Thread', 'Engaging Twitter thread reviewing movies/shows', '{"thread": [{"tweet": "Just watched [MOVIE TITLE] and I have THOUGHTS 🎬\n\nA thread 🧵"}, {"tweet": "1/ The cinematography was absolutely stunning. Every frame looked like a painting."}, {"tweet": "2/ The acting? *Chef''s kiss* [ACTOR NAME] deserves all the awards for this performance."}, {"tweet": "3/ The plot twist in the third act completely broke me. Did NOT see that coming."}, {"tweet": "4/ Minor issues: pacing dragged in the middle, some dialogue felt forced"}, {"tweet": "5/ Overall: [X]/10\n\nWould definitely recommend to [TARGET AUDIENCE]\n\nHave you seen it? What did you think? 👇"}], "engagement_questions": ["What''s your favorite movie this year?", "Any recommendations for similar films?"], "hashtags": ["#MovieReview", "#FilmTwitter", "#NowWatching"]}'::jsonb, 'content_creation', 'entertainment', 'twitter', 'humorous', 'caption', true, ARRAY['movies', 'review', 'twitter', 'thread', 'entertainment'], 'intermediate', 15);

-- 8. Education YouTube Title
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Educational Video Title', 'SEO-optimized YouTube title for educational content', '{"headline": "[TOPIC] Explained in [NUMBER] Minutes | [BENEFIT]", "alternative_titles": ["The Complete Guide to [TOPIC] for Beginners", "[TOPIC]: Everything You Need to Know", "Learn [TOPIC] Fast: [NUMBER] Step Tutorial"], "seo_keywords": ["[topic] tutorial", "learn [topic]", "[topic] explained"], "description_template": "In this video, we''ll cover:\n\n✅ [POINT 1]\n✅ [POINT 2]\n✅ [POINT 3]\n\nBy the end, you''ll understand [OUTCOME]."}'::jsonb, 'content_creation', 'education', 'youtube', 'educational', 'headline', true, ARRAY['education', 'youtube', 'tutorial', 'seo', 'headline'], 'beginner', 5);

-- 9. Fitness Hashtag Set
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Gym Hashtag Collection', 'Comprehensive fitness hashtags for Instagram posts', '{"hashtags": ["#FitnessMotivation", "#WorkoutWednesday", "#GymLife", "#FitFam", "#NoExcuses", "#TrainHard", "#FitnessJourney", "#HealthyLifestyle", "#GetStrong", "#FitnessGoals"], "niche_tags": ["#WeightTraining", "#Cardio", "#Yoga", "#CrossFit"], "engagement_tags": ["#FollowForFollow", "#LikeForLike", "#FitnessCommunity"]}'::jsonb, 'social_media', 'fitness', 'instagram', 'enthusiastic', 'hashtag', true, ARRAY['fitness', 'hashtags', 'gym', 'instagram', 'engagement'], 'beginner', 2);

-- 10. Tech Product Launch Headline
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Product Launch Announcement', 'Compelling headline for tech product launches', '{"headline": "Introducing [PRODUCT NAME]: The [ADJECTIVE] [PRODUCT TYPE] That [BENEFIT]", "subheadline": "Built for [TARGET AUDIENCE] who want [OUTCOME]", "key_points": ["[FEATURE 1] that [BENEFIT]", "[FEATURE 2] for [USE CASE]", "[FEATURE 3] to [SOLVE PROBLEM]"], "cta": "Learn more at [WEBSITE] | Available [DATE]"}'::jsonb, 'content_creation', 'tech', 'universal', 'professional', 'headline', true, ARRAY['tech', 'product', 'launch', 'headline', 'announcement'], 'intermediate', 10);

-- 11. Cooking Recipe Blog Post
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Recipe Blog Post Structure', 'Complete structure for recipe blog posts', '{"title": "[DISH NAME]: The [ADJECTIVE] [CUISINE] Recipe You''ll Make Again", "intro": "Personal story + why this recipe is special + what makes it different", "prep_time": "[X] minutes", "cook_time": "[Y] minutes", "servings": "[Z]", "ingredients_section": "List with measurements, alternatives noted", "instructions": "Step-by-step with tips", "nutrition_info": "Optional: calories, macros", "variations": "How to customize", "storage_tips": "How to store leftovers", "conclusion": "Encourage to try, ask for photos, social sharing"}'::jsonb, 'content_creation', 'cooking', 'universal', 'casual', 'blog_outline', true, ARRAY['cooking', 'recipe', 'blog', 'food', 'tutorial'], 'intermediate', 25);

-- 12. Fashion OOTD Caption
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Outfit of the Day Post', 'Stylish caption for daily outfit posts', '{"caption": "OOTD ✨\n\n[DESCRIBE OUTFIT]\n\n[SHARE STYLING TIP OR STORY]\n\nWhere''s your favorite place to shop [ITEM TYPE]? Drop your recommendations below! 👇\n\n#OOTD #StyleInspo #FashionDaily", "outfit_details": "Top: [BRAND/STORE]\nBottom: [BRAND/STORE]\nShoes: [BRAND/STORE]\nAccessories: [ITEMS]", "styling_tip": "[TIP ABOUT THIS OUTFIT]"}'::jsonb, 'social_media', 'fashion', 'instagram', 'casual', 'caption', true, ARRAY['fashion', 'ootd', 'outfit', 'style', 'instagram'], 'beginner', 5);

-- 13. Business Email Subject Line
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Professional Email Subject', 'Effective subject lines for business emails', '{"headlines": ["[ACTION] Request: [TOPIC]", "Following up on [TOPIC]", "[URGENCY] [TOPIC] - [DEADLINE]", "Quick question about [TOPIC]", "[BENEFIT] Opportunity: [TOPIC]"], "best_practices": "Keep under 50 characters, be specific, include value proposition", "examples": ["Partnership Opportunity: [COMPANY NAME]", "Meeting Request: [DATE] Availability", "Proposal: [PROJECT NAME]"]}'::jsonb, 'professional', 'business', 'universal', 'professional', 'headline', true, ARRAY['business', 'email', 'subject', 'professional', 'communication'], 'beginner', 3);

-- 14. Travel Instagram Story Template
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Travel Story Series', 'Instagram story templates for travel content', '{"story_sequence": ["Location tag + photo", "Food highlight with price", "Local tip or fact", "Behind-the-scenes moment", "Call to action: Ask me anything"], "text_overlays": ["📍 [LOCATION]", "💰 [COST]", "💡 Pro tip:", "📸 [PHOTO DESCRIPTION]", "❓ Ask me anything"], "stickers": ["Location", "Poll", "Question", "Music"], "cta": "Swipe up for full guide"}'::jsonb, 'social_media', 'travel', 'instagram', 'enthusiastic', 'content_idea', true, ARRAY['travel', 'instagram', 'stories', 'social', 'content'], 'beginner', 8);

-- 15. Education LinkedIn Article
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Educational Article Outline', 'Structure for educational LinkedIn articles', '{"title": "[TOPIC]: What [AUDIENCE] Need to Know in [YEAR]", "hook": "Startling statistic or question", "sections": [{"heading": "The Problem", "content": "Define the issue"}, {"heading": "Why It Matters", "content": "Impact and consequences"}, {"heading": "The Solution", "content": "Practical approaches"}, {"heading": "Real-World Examples", "content": "Case studies"}, {"heading": "Key Takeaways", "content": "Actionable points"}], "conclusion": "Call to action, encourage discussion", "engagement_prompt": "What''s your experience with [TOPIC]?"}'::jsonb, 'content_creation', 'education', 'linkedin', 'educational', 'blog_outline', true, ARRAY['education', 'linkedin', 'article', 'professional', 'thought-leadership'], 'intermediate', 25);

-- 16. Entertainment Podcast Description
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Podcast Episode Description', 'Engaging description for podcast episodes', '{"description": "In this episode, we dive deep into [TOPIC] with [GUEST NAME], [GUEST TITLE].\n\n🎙️ What we cover:\n• [TOPIC 1]\n• [TOPIC 2]\n• [TOPIC 3]\n\n💡 Key takeaways:\n- [INSIGHT 1]\n- [INSIGHT 2]\n- [INSIGHT 3]\n\n🔗 Links mentioned:\n[LINK 1]\n[LINK 2]\n\n📱 Connect with us:\nWebsite: [URL]\nInstagram: [@HANDLE]\nTwitter: [@HANDLE]\n\n⏱️ Episode length: [X] minutes", "seo_keywords": ["[topic] podcast", "[guest name]", "entertainment"]}'::jsonb, 'content_creation', 'entertainment', 'universal', 'casual', 'description', true, ARRAY['podcast', 'entertainment', 'description', 'audio', 'content'], 'beginner', 10);

-- 17. Fitness Transformation Post
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Fitness Journey Update', 'Motivational post for fitness transformations', '{"caption": "[TIME PERIOD] update on my fitness journey 💪\n\nStarting point: [STATS]\nCurrent: [STATS]\n\nWhat changed:\n✅ [CHANGE 1]\n✅ [CHANGE 2]\n✅ [CHANGE 3]\n\nIt wasn''t easy, but consistency is key. Every small step counts.\n\nIf you''re on your own journey, remember: progress > perfection.\n\nWhat''s your biggest fitness goal right now? Let''s motivate each other! 🔥", "before_after": "Include side-by-side comparison", "key_tips": ["[TIP 1]", "[TIP 2]", "[TIP 3]"], "hashtags": ["#FitnessJourney", "#Transformation", "#ProgressNotPerfection"]}'::jsonb, 'social_media', 'fitness', 'instagram', 'inspirational', 'caption', true, ARRAY['fitness', 'transformation', 'journey', 'motivation', 'progress'], 'beginner', 8);

-- 18. Tech Tutorial Script
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Tech How-To Video Script', 'Script structure for technical tutorial videos', '{"hook": "Today I''ll show you how to [ACHIEVEMENT] in just [TIME]", "intro": "Problem this solves + who it''s for", "prerequisites": "What you need before starting", "steps": [{"step": 1, "action": "[ACTION 1]", "explanation": "[WHY]"}, {"step": 2, "action": "[ACTION 2]", "explanation": "[WHY]"}, {"step": 3, "action": "[ACTION 3]", "explanation": "[WHY]"}], "common_mistakes": "What to avoid", "recap": "Quick summary of steps", "cta": "Like if this helped, subscribe for more tutorials"}'::jsonb, 'content_creation', 'tech', 'youtube', 'educational', 'script', true, ARRAY['tech', 'tutorial', 'script', 'youtube', 'how-to'], 'intermediate', 20);

-- 19. Cooking Meal Prep Content
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Meal Prep Sunday Guide', 'Complete meal prep content structure', '{"title": "Sunday Meal Prep: [NUMBER] Meals Under $[AMOUNT]", "intro": "Why meal prep + benefits", "shopping_list": "All ingredients needed", "prep_timeline": "Step-by-step prep order", "storage_tips": "How to store each item", "reheating_instructions": "Best way to reheat", "cost_breakdown": "Price per meal", "variations": "How to customize", "cta": "Save this post for your next meal prep session!"}'::jsonb, 'content_creation', 'cooking', 'universal', 'casual', 'blog_outline', true, ARRAY['cooking', 'meal prep', 'budget', 'meal planning', 'food'], 'intermediate', 20);

-- 20. Fashion Brand Collaboration Post
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Brand Partnership Announcement', 'Professional post for brand collaborations', '{"caption": "Excited to partner with [BRAND NAME]! ✨\n\nI''ve been using their [PRODUCT TYPE] for [TIME] and honestly, [GENUINE REASON].\n\nWhat I love:\n💫 [FEATURE 1]\n💫 [FEATURE 2]\n💫 [FEATURE 3]\n\nUse code [CODE] for [DISCOUNT]% off your first order!\n\n#Ad #Sponsored #BrandPartner", "disclosure": "This post is sponsored, but all opinions are my own", "product_highlights": ["[PRODUCT 1]", "[PRODUCT 2]", "[PRODUCT 3]"], "affiliate_link": "[LINK]"}'::jsonb, 'social_media', 'fashion', 'instagram', 'enthusiastic', 'caption', true, ARRAY['fashion', 'collaboration', 'sponsored', 'brand', 'partnership'], 'beginner', 10);

-- 21. Business Case Study Outline
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Business Case Study Structure', 'Professional case study format', '{"title": "How [COMPANY] [ACHIEVEMENT] Using [METHOD/SOLUTION]", "executive_summary": "Brief overview of challenge and solution", "sections": [{"heading": "The Challenge", "content": "Problem faced, impact, constraints"}, {"heading": "The Solution", "content": "Approach taken, methodology"}, {"heading": "Implementation", "content": "Steps, timeline, resources"}, {"heading": "Results", "content": "Metrics, outcomes, ROI"}, {"heading": "Key Learnings", "content": "Insights, best practices"}], "conclusion": "Summary and next steps", "cta": "Want similar results? Let''s talk."}'::jsonb, 'professional', 'business', 'universal', 'professional', 'blog_outline', true, ARRAY['business', 'case study', 'professional', 'results', 'strategy'], 'advanced', 35);

-- 22. Travel Packing List Content
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Ultimate Packing Guide', 'Comprehensive packing list template', '{"title": "The Ultimate [DESTINATION TYPE] Packing List", "trip_duration": "[X] days", "climate": "[CLIMATE TYPE]", "categories": [{"category": "Clothing", "items": ["[ITEM 1]", "[ITEM 2]", "[ITEM 3]"]}, {"category": "Electronics", "items": ["[ITEM 1]", "[ITEM 2]"]}, {"category": "Toiletries", "items": ["[ITEM 1]", "[ITEM 2]"]}, {"category": "Documents", "items": ["[ITEM 1]", "[ITEM 2]"]}], "pro_tips": ["[TIP 1]", "[TIP 2]", "[TIP 3]"], "what_to_leave": "Items you don''t need", "cta": "Save this for your next trip!"}'::jsonb, 'content_creation', 'travel', 'universal', 'educational', 'blog_outline', true, ARRAY['travel', 'packing', 'guide', 'checklist', 'tips'], 'beginner', 15);

-- 23. Education Study Tips Post
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Study Strategy Guide', 'Educational post sharing study techniques', '{"caption": "Top [NUMBER] study tips that actually work 📚\n\n1️⃣ [TIP 1] - [EXPLANATION]\n2️⃣ [TIP 2] - [EXPLANATION]\n3️⃣ [TIP 3] - [EXPLANATION]\n4️⃣ [TIP 4] - [EXPLANATION]\n5️⃣ [TIP 5] - [EXPLANATION]\n\nWhich one will you try? Save this post for exam season! 💪\n\n#StudyTips #Productivity #StudentLife", "methodology": "[STUDY METHOD NAME]", "time_management": "[TIME MANAGEMENT TIP]", "resources": "[HELPFUL RESOURCES]"}'::jsonb, 'content_creation', 'education', 'instagram', 'educational', 'caption', true, ARRAY['education', 'study tips', 'learning', 'productivity', 'students'], 'beginner', 8);

-- 24. Entertainment Watchlist Content
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Monthly Watchlist Post', 'Engaging post sharing entertainment recommendations', '{"caption": "[MONTH] Watchlist 🎬\n\nWhat I''m watching this month:\n\n📺 [SHOW 1] - [BRIEF REASON]\n🎬 [MOVIE 1] - [BRIEF REASON]\n📚 [BOOK 1] - [BRIEF REASON]\n\nWhat''s on your list? Drop your recommendations below! 👇\n\n#Watchlist #Entertainment #Recommendations", "categories": {"shows": ["[SHOW 1]", "[SHOW 2]"], "movies": ["[MOVIE 1]", "[MOVIE 2]"], "books": ["[BOOK 1]", "[BOOK 2]"]}, "ratings": "Include personal ratings", "engagement": "Ask followers for their recommendations"}'::jsonb, 'social_media', 'entertainment', 'instagram', 'casual', 'content_idea', true, ARRAY['entertainment', 'watchlist', 'recommendations', 'movies', 'shows'], 'beginner', 5);

-- 25. General Productivity Tips
INSERT INTO content_templates (id, user_id, name, description, template_data, category, niche, platform, voice, template_type, is_public, tags, difficulty_level, estimated_time_minutes) VALUES 
(gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'Daily Productivity Hacks', 'Universal productivity tips for any niche', '{"caption": "[NUMBER] productivity hacks that changed my life 🚀\n\n✅ [HACK 1] - [BENEFIT]\n✅ [HACK 2] - [BENEFIT]\n✅ [HACK 3] - [BENEFIT]\n✅ [HACK 4] - [BENEFIT]\n✅ [HACK 5] - [BENEFIT]\n\nWhich one will you implement today? Let me know in the comments! 💬\n\n#Productivity #LifeHacks #SelfImprovement", "categories": {"morning_routine": "[TIP]", "time_management": "[TIP]", "focus": "[TIP]", "energy": "[TIP]"}, "actionable": "Each tip should be immediately implementable"}'::jsonb, 'content_creation', 'general', 'universal', 'educational', 'caption', true, ARRAY['productivity', 'life hacks', 'self-improvement', 'tips', 'general'], 'beginner', 7);
