import { NextRequest, NextResponse } from 'next/server'
import { sql } from '@/lib/db'
import { getUserIdFromRequest } from '@/lib/subscription'
import { nanoid } from 'nanoid'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

// POST: Add tags to content
export async function POST(request: NextRequest) {
  try {
    const userId = await getUserIdFromRequest(request)
    
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    if (!sql) {
      return NextResponse.json(
        { error: 'Database not available' },
        { status: 503 }
      )
    }

    const body = await request.json()
    const { contentId, contentType, tags, isAutoGenerated = false } = body

    if (!contentId || !contentType || !tags || !Array.isArray(tags)) {
      return NextResponse.json(
        { error: 'contentId, contentType, and tags array are required' },
        { status: 400 }
      )
    }

    // First, ensure tags exist
    const tagIds = []
    for (const tagName of tags) {
      // Check if tag exists
      const existing = await sql`
        SELECT id FROM tags WHERE LOWER(name) = LOWER(${tagName.trim()})
      `

      let tagId
      if (existing.length > 0) {
        tagId = existing[0].id
      } else {
        // Create new tag
        const newTag = await sql`
          INSERT INTO tags (id, name, category, color, created_at, updated_at)
          VALUES (${nanoid()}, ${tagName.trim().toLowerCase()}, 'general', '#3B82F6', NOW(), NOW())
          RETURNING id
        `
        tagId = newTag[0].id
      }

      tagIds.push({ name: tagName, id: tagId })
    }

    // Delete existing tags for this content
    await sql`
      DELETE FROM content_tags
      WHERE content_id = ${contentId}
      AND content_type = ${contentType}
      AND user_id = ${userId}
    `

    // Insert new tags
    const insertedTags = []
    for (const { name, id: tagId } of tagIds) {
      const result = await sql`
        INSERT INTO content_tags (
          id, content_id, content_type, tag_id, user_id, 
          confidence_score, is_auto_generated, created_at
        ) VALUES (
          ${nanoid()}, ${contentId}, ${contentType}, ${tagId}, ${userId},
          1.0, ${isAutoGenerated}, NOW()
        )
        ON CONFLICT (content_id, content_type, tag_id, user_id) DO UPDATE
        SET updated_at = NOW()
        RETURNING *
      `
      insertedTags.push(result[0])
    }

    return NextResponse.json({ 
      success: true,
      tags: insertedTags,
      message: `${insertedTags.length} tags added`
    })

  } catch (error) {
    console.error('Error adding tags:', error)
    return NextResponse.json(
      { error: 'Failed to add tags' },
      { status: 500 }
    )
  }
}

// DELETE: Remove tags from content
export async function DELETE(request: NextRequest) {
  try {
    const userId = await getUserIdFromRequest(request)
    
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    if (!sql) {
      return NextResponse.json(
        { error: 'Database not available' },
        { status: 503 }
      )
    }

    const body = await request.json()
    const { contentId, contentType, tags } = body

    if (!contentId || !contentType) {
      return NextResponse.json(
        { error: 'contentId and contentType are required' },
        { status: 400 }
      )
    }

    if (tags && Array.isArray(tags)) {
      // Delete specific tags
      for (const tagName of tags) {
        const tag = await sql`
          SELECT id FROM tags WHERE LOWER(name) = LOWER(${tagName.trim()})
        `

        if (tag.length > 0) {
          await sql`
            DELETE FROM content_tags
            WHERE content_id = ${contentId}
            AND content_type = ${contentType}
            AND user_id = ${userId}
            AND tag_id = ${tag[0].id}
          `
        }
      }
    } else {
      // Delete all tags for this content
      await sql`
        DELETE FROM content_tags
        WHERE content_id = ${contentId}
        AND content_type = ${contentType}
        AND user_id = ${userId}
      `
    }

    return NextResponse.json({ 
      success: true,
      message: 'Tags removed successfully'
    })

  } catch (error) {
    console.error('Error removing tags:', error)
    return NextResponse.json(
      { error: 'Failed to remove tags' },
      { status: 500 }
    )
  }
}
