'use client'

import React, { useMemo, useState } from 'react'
import { ToolAccessGate } from '@/components/ToolAccessGate'
import { useLanguage } from '@/lib/i18n/LanguageContext'

type Platform =
  | 'Instagram'
  | 'TikTok'
  | 'YouTube'
  | 'X (Twitter)'
  | 'LinkedIn'
  | 'Facebook'
  | 'Other'

function toNumber(value: string): number {
  const n = Number(value.replace(/,/g, '').trim())
  return Number.isFinite(n) ? n : 0
}

function pct(n: number): string {
  if (!Number.isFinite(n)) return '0.00%'
  return `${n.toFixed(2)}%`
}

function money(n: number): string {
  if (!Number.isFinite(n)) return '$0.00'
  return `$${n.toFixed(2)}`
}

const copy = {
  en: {
    toolName: 'Social Media Report Generator',
    toolDescription:
      'Generates professional social media performance reports. Input metrics for Instagram, TikTok, YouTube, Twitter, or LinkedIn to create comprehensive reports with analytics, insights, and visualizations.',
    howToUse: [
      { label: 'Select platform:', text: 'Choose Instagram, TikTok, YouTube, Twitter, or LinkedIn' },
      { label: 'Enter campaign name:', text: 'Name your report/campaign' },
      { label: 'Input metrics:', text: 'Enter followers, posts, engagement, reach, impressions, etc.' },
      { label: 'Click "Generate Report":', text: 'Create a comprehensive performance report' },
      { label: 'Download:', text: 'Export the report as PDF or copy the data' },
    ],
    howToUseTitle: 'How to Use This Tool',
    whatItDoes: 'What It Does',
    whatItDoesBody:
      'Generates a clean, copy-ready performance report from your social metrics, including engagement rate, CTR, and paid media KPIs like CPC/CPM.',
    howToUseInner: 'How to Use',
    howToUseSteps: [
      'Enter campaign details (platform + date range).',
      'Paste metrics from your analytics dashboard.',
      'Copy or download the generated Markdown report.',
    ],
    title: 'Social Media Report Generator',
    supportedPlatforms: 'Supported Platforms:',
    platform: 'Platform',
    campaignName: 'Campaign name',
    campaignPlaceholder: 'e.g., January product launch',
    startDate: 'Start date',
    endDate: 'End date',
    impressions: 'Impressions',
    reach: 'Reach',
    clicks: 'Clicks',
    likes: 'Likes',
    comments: 'Comments',
    shares: 'Shares',
    saves: 'Saves',
    followersGained: 'Followers gained',
    spendOptional: 'Spend (optional)',
    quickKpis: 'Quick KPIs',
    engagementRateImpressions: (rate: string, count: string) =>
      `Engagement rate (impressions): ${rate} (${count} engagements)`,
    engagementRateReach: (rate: string) => `Engagement rate (reach): ${rate}`,
    ctr: (rate: string, count: string) => `CTR: ${rate} (${count} clicks)`,
    cpc: (val: string) => `CPC: ${val}`,
    cpm: (val: string) => `CPM: ${val}`,
    copyReport: 'Copy report',
    downloadMd: 'Download .md',
    copiedAlert: 'Report copied to clipboard!',
    defaultTitle: 'Social Media Performance',
    dateOngoing: (start: string) => `${start} → (ongoing)`,
    dateUnknown: (end: string) => `(unknown) → ${end}`,
    dateRange: (start: string, end: string) => `${start} → ${end}`,
    notSpecified: 'Not specified',
    dateRangeLabel: 'Date range',
    reportSuffix: 'Report',
    keyMetrics: 'Key Metrics',
    labelImpressions: 'Impressions',
    labelReach: 'Reach',
    labelClicks: 'Clicks',
    labelEngagements: 'Engagements',
    engagementsDetail: '(likes + comments + shares + saves)',
    labelFollowersGained: 'Followers gained',
    labelSpend: 'Spend',
    spendIfPaid: '(if paid)',
    kpis: 'KPIs',
    kpiErImpressions: 'Engagement rate (by impressions)',
    kpiErReach: 'Engagement rate (by reach)',
    kpiCtr: 'CTR',
    kpiCpc: 'CPC',
    kpiCpm: 'CPM',
    kpiCostPerFollower: 'Cost per follower',
    na: 'N/A',
    insights: 'Insights',
    notEnoughInsights: 'Not enough data to generate insights yet.',
    recommendations: 'Recommendations',
    generatedBy: 'Generated by Social Media Report Generator.',
    insightEngagementsZero: 'Engagements are at 0 — double-check the input metrics.',
    insightCtrLow: 'CTR is low — test stronger hooks, clearer CTAs, and more relevant landing pages.',
    insightErStrong: 'Engagement rate is strong — consider scaling the winning creative format.',
    insightErWeak: 'Engagement rate is weak — test new content pillars, posting times, and formats.',
    insightSpendNoClicks: 'Spend is recorded but clicks are 0 — confirm attribution/UTMs or tracking.',
    insightFollowerGrowth: 'Follower growth is positive — replicate the posts that drove follows and add "follow" CTAs.',
    recRepurpose: 'Repurpose the best-performing posts into 3–5 variants (hook, thumbnail, caption) and A/B test them.',
    recCta: 'Add a clear CTA on every post and align the landing page message with the post promise.',
    recTrack: 'Track results weekly: impressions, engagements, CTR, follower growth, and cost metrics (if paid).',
  },
  es: {
    toolName: 'Generador de informes de redes sociales',
    toolDescription:
      'Genera informes profesionales de rendimiento en redes sociales. Ingresa métricas de Instagram, TikTok, YouTube, Twitter o LinkedIn para crear informes completos con analítica, insights y visualizaciones.',
    howToUse: [
      { label: 'Selecciona plataforma:', text: 'Elige Instagram, TikTok, YouTube, Twitter o LinkedIn' },
      { label: 'Ingresa nombre de campaña:', text: 'Nombra tu informe/campaña' },
      { label: 'Ingresa métricas:', text: 'Ingresa seguidores, publicaciones, engagement, alcance, impresiones, etc.' },
      { label: 'Haz clic en "Generar informe":', text: 'Crea un informe de rendimiento completo' },
      { label: 'Descarga:', text: 'Exporta el informe como PDF o copia los datos' },
    ],
    howToUseTitle: 'Cómo usar esta herramienta',
    whatItDoes: 'Qué hace',
    whatItDoesBody:
      'Genera un informe de rendimiento limpio y listo para copiar a partir de tus métricas sociales, incluyendo tasa de engagement, CTR y KPIs de medios pagados como CPC/CPM.',
    howToUseInner: 'Cómo usar',
    howToUseSteps: [
      'Ingresa detalles de campaña (plataforma + rango de fechas).',
      'Pega métricas de tu panel de analítica.',
      'Copia o descarga el informe Markdown generado.',
    ],
    title: 'Generador de informes de redes sociales',
    supportedPlatforms: 'Plataformas compatibles:',
    platform: 'Plataforma',
    campaignName: 'Nombre de campaña',
    campaignPlaceholder: 'ej., Lanzamiento de producto en enero',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    impressions: 'Impresiones',
    reach: 'Alcance',
    clicks: 'Clics',
    likes: 'Me gusta',
    comments: 'Comentarios',
    shares: 'Compartidos',
    saves: 'Guardados',
    followersGained: 'Seguidores ganados',
    spendOptional: 'Gasto (opcional)',
    quickKpis: 'KPIs rápidos',
    engagementRateImpressions: (rate: string, count: string) =>
      `Tasa de engagement (impresiones): ${rate} (${count} interacciones)`,
    engagementRateReach: (rate: string) => `Tasa de engagement (alcance): ${rate}`,
    ctr: (rate: string, count: string) => `CTR: ${rate} (${count} clics)`,
    cpc: (val: string) => `CPC: ${val}`,
    cpm: (val: string) => `CPM: ${val}`,
    copyReport: 'Copiar informe',
    downloadMd: 'Descargar .md',
    copiedAlert: '¡Informe copiado al portapapeles!',
    defaultTitle: 'Rendimiento en redes sociales',
    dateOngoing: (start: string) => `${start} → (en curso)`,
    dateUnknown: (end: string) => `(desconocido) → ${end}`,
    dateRange: (start: string, end: string) => `${start} → ${end}`,
    notSpecified: 'No especificado',
    dateRangeLabel: 'Rango de fechas',
    reportSuffix: 'Informe',
    keyMetrics: 'Métricas clave',
    labelImpressions: 'Impresiones',
    labelReach: 'Alcance',
    labelClicks: 'Clics',
    labelEngagements: 'Interacciones',
    engagementsDetail: '(me gusta + comentarios + compartidos + guardados)',
    labelFollowersGained: 'Seguidores ganados',
    labelSpend: 'Gasto',
    spendIfPaid: '(si es pagado)',
    kpis: 'KPIs',
    kpiErImpressions: 'Tasa de engagement (por impresiones)',
    kpiErReach: 'Tasa de engagement (por alcance)',
    kpiCtr: 'CTR',
    kpiCpc: 'CPC',
    kpiCpm: 'CPM',
    kpiCostPerFollower: 'Costo por seguidor',
    na: 'N/D',
    insights: 'Insights',
    notEnoughInsights: 'Aún no hay suficientes datos para generar insights.',
    recommendations: 'Recomendaciones',
    generatedBy: 'Generado por Social Media Report Generator.',
    insightEngagementsZero: 'Las interacciones están en 0 — verifica las métricas ingresadas.',
    insightCtrLow: 'El CTR es bajo — prueba ganchos más fuertes, CTAs más claros y landing pages más relevantes.',
    insightErStrong: 'La tasa de engagement es fuerte — considera escalar el formato creativo ganador.',
    insightErWeak: 'La tasa de engagement es débil — prueba nuevos pilares de contenido, horarios y formatos.',
    insightSpendNoClicks: 'Hay gasto registrado pero 0 clics — confirma atribución/UTMs o el rastreo.',
    insightFollowerGrowth: 'El crecimiento de seguidores es positivo — replica las publicaciones que generaron follows y agrega CTAs de "seguir".',
    recRepurpose: 'Reutiliza las publicaciones con mejor rendimiento en 3–5 variantes (gancho, miniatura, caption) y haz pruebas A/B.',
    recCta: 'Agrega un CTA claro en cada publicación y alinea el mensaje de la landing page con la promesa del post.',
    recTrack: 'Rastrea resultados semanalmente: impresiones, interacciones, CTR, crecimiento de seguidores y métricas de costo (si es pagado).',
  },
}

function SocialMediaReportGeneratorContent() {
  const { language } = useLanguage()
  const c = copy[language]
  const [platform, setPlatform] = useState<Platform>('Instagram')
  const [campaignName, setCampaignName] = useState('')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')

  const [impressions, setImpressions] = useState('0')
  const [reach, setReach] = useState('0')
  const [clicks, setClicks] = useState('0')
  const [likes, setLikes] = useState('0')
  const [comments, setComments] = useState('0')
  const [shares, setShares] = useState('0')
  const [saves, setSaves] = useState('0')
  const [followersGained, setFollowersGained] = useState('0')
  const [spend, setSpend] = useState('0')

  const computed = useMemo(() => {
    const imp = Math.max(0, toNumber(impressions))
    const rch = Math.max(0, toNumber(reach))
    const clk = Math.max(0, toNumber(clicks))
    const l = Math.max(0, toNumber(likes))
    const cm = Math.max(0, toNumber(comments))
    const sh = Math.max(0, toNumber(shares))
    const sv = Math.max(0, toNumber(saves))
    const fg = Math.max(0, toNumber(followersGained))
    const sp = Math.max(0, toNumber(spend))

    const engagements = l + cm + sh + sv
    const erImpressions = imp > 0 ? (engagements / imp) * 100 : 0
    const erReach = rch > 0 ? (engagements / rch) * 100 : 0
    const ctr = imp > 0 ? (clk / imp) * 100 : 0

    const cpc = clk > 0 ? sp / clk : 0
    const cpm = imp > 0 ? (sp / imp) * 1000 : 0
    const cpf = fg > 0 ? sp / fg : 0

    const insights: string[] = []
    if (imp > 0 && engagements === 0) insights.push(c.insightEngagementsZero)
    if (ctr < 0.5 && imp > 0) insights.push(c.insightCtrLow)
    if (erImpressions >= 3) insights.push(c.insightErStrong)
    if (erImpressions > 0 && erImpressions < 1) insights.push(c.insightErWeak)
    if (sp > 0 && clk === 0) insights.push(c.insightSpendNoClicks)
    if (fg > 0) insights.push(c.insightFollowerGrowth)

    const recommendations: string[] = [c.recRepurpose, c.recCta, c.recTrack]

    return {
      imp,
      rch,
      clk,
      l,
      cm,
      sh,
      sv,
      fg,
      sp,
      engagements,
      erImpressions,
      erReach,
      ctr,
      cpc,
      cpm,
      cpf,
      insights,
      recommendations,
    }
  }, [
    impressions,
    reach,
    clicks,
    likes,
    comments,
    shares,
    saves,
    followersGained,
    spend,
    c,
  ])

  const reportMarkdown = useMemo(() => {
    const title = campaignName.trim() ? campaignName.trim() : c.defaultTitle
    const range =
      startDate && endDate
        ? c.dateRange(startDate, endDate)
        : startDate
        ? c.dateOngoing(startDate)
        : endDate
        ? c.dateUnknown(endDate)
        : c.notSpecified

    return [
      `## ${title} ${c.reportSuffix}`,
      ``,
      `- **${c.platform}**: ${platform}`,
      `- **${c.dateRangeLabel}**: ${range}`,
      ``,
      `### ${c.keyMetrics}`,
      `- **${c.labelImpressions}**: ${computed.imp.toLocaleString()}`,
      `- **${c.labelReach}**: ${computed.rch.toLocaleString()}`,
      `- **${c.labelClicks}**: ${computed.clk.toLocaleString()}`,
      `- **${c.labelEngagements}** ${c.engagementsDetail}: ${computed.engagements.toLocaleString()}`,
      `- **${c.labelFollowersGained}**: ${computed.fg.toLocaleString()}`,
      `- **${c.labelSpend}** ${c.spendIfPaid}: ${money(computed.sp)}`,
      ``,
      `### ${c.kpis}`,
      `- **${c.kpiErImpressions}**: ${pct(computed.erImpressions)}`,
      `- **${c.kpiErReach}**: ${pct(computed.erReach)}`,
      `- **${c.kpiCtr}**: ${pct(computed.ctr)}`,
      `- **${c.kpiCpc}**: ${computed.sp > 0 ? money(computed.cpc) : c.na}`,
      `- **${c.kpiCpm}**: ${computed.sp > 0 ? money(computed.cpm) : c.na}`,
      `- **${c.kpiCostPerFollower}**: ${computed.sp > 0 ? money(computed.cpf) : c.na}`,
      ``,
      `### ${c.insights}`,
      ...(computed.insights.length ? computed.insights.map((x) => `- ${x}`) : [`- ${c.notEnoughInsights}`]),
      ``,
      `### ${c.recommendations}`,
      ...computed.recommendations.map((x) => `- ${x}`),
      ``,
      `---`,
      c.generatedBy,
      ``,
    ].join('\n')
  }, [campaignName, platform, startDate, endDate, computed, c])

  const handleCopyReport = async () => {
    await navigator.clipboard.writeText(reportMarkdown)
    alert(c.copiedAlert)
  }

  const download = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(campaignName.trim() || 'social-media-report')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '')}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 p-8">
      <div className="max-w-5xl mx-auto">
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 mb-8 border border-gray-200 dark:border-gray-700">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">{c.howToUseTitle}</h2>
          <div className="space-y-3 text-sm text-gray-700 dark:text-gray-300">
            <div>
              <h3 className="font-semibold text-gray-900 dark:text-white mb-1">{c.whatItDoes}</h3>
              <p>{c.whatItDoesBody}</p>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 dark:text-white mb-1">{c.howToUseInner}</h3>
              <ol className="list-decimal list-inside space-y-1 ml-2">
                {c.howToUseSteps.map((step, i) => (
                  <li key={i}>{step}</li>
                ))}
              </ol>
            </div>
          </div>
        </div>

        <h1 className="text-3xl font-bold mb-4 text-gray-900 dark:text-white">{c.title}</h1>

        <div className="bg-accent-50 dark:bg-accent-900/20 border border-accent-200 dark:border-accent-800 rounded-lg p-4 mb-6">
          <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">{c.supportedPlatforms}</p>
          <div className="flex flex-wrap gap-2">
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">📸 Instagram</span>
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">🎵 TikTok</span>
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">📺 YouTube</span>
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">🐦 Twitter/X</span>
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">💼 LinkedIn</span>
            <span className="px-3 py-1 bg-white dark:bg-gray-800 rounded-full text-xs font-medium text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">📘 Facebook</span>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{c.platform}</label>
                <select
                  value={platform}
                  onChange={(e) => setPlatform(e.target.value as Platform)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                >
                  {['Instagram', 'TikTok', 'YouTube', 'X (Twitter)', 'LinkedIn', 'Facebook', 'Other'].map((p) => (
                    <option key={p} value={p}>
                      {p}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{c.campaignName}</label>
                <input
                  value={campaignName}
                  onChange={(e) => setCampaignName(e.target.value)}
                  placeholder={c.campaignPlaceholder}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder:text-gray-500 dark:placeholder:text-gray-400"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{c.startDate}</label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{c.endDate}</label>
                <input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <MetricInput label={c.impressions} value={impressions} onChange={setImpressions} />
              <MetricInput label={c.reach} value={reach} onChange={setReach} />
              <MetricInput label={c.clicks} value={clicks} onChange={setClicks} />
              <MetricInput label={c.likes} value={likes} onChange={setLikes} />
              <MetricInput label={c.comments} value={comments} onChange={setComments} />
              <MetricInput label={c.shares} value={shares} onChange={setShares} />
              <MetricInput label={c.saves} value={saves} onChange={setSaves} />
              <MetricInput label={c.followersGained} value={followersGained} onChange={setFollowersGained} />
              <MetricInput label={c.spendOptional} value={spend} onChange={setSpend} />
            </div>

            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4">
              <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-3">{c.quickKpis}</h2>
              <ul className="text-sm text-gray-700 dark:text-gray-300 space-y-1">
                <li>
                  {c.engagementRateImpressions(pct(computed.erImpressions), computed.engagements.toLocaleString())}
                </li>
                <li>{c.engagementRateReach(pct(computed.erReach))}</li>
                <li>{c.ctr(pct(computed.ctr), computed.clk.toLocaleString())}</li>
                <li>{c.cpc(computed.sp > 0 ? money(computed.cpc) : c.na)}</li>
                <li>{c.cpm(computed.sp > 0 ? money(computed.cpm) : c.na)}</li>
              </ul>
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex flex-wrap gap-2">
              <button
                onClick={handleCopyReport}
                className="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md text-sm transition-colors"
              >
                {c.copyReport}
              </button>
              <button
                onClick={download}
                className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-md text-sm transition-colors"
              >
                {c.downloadMd}
              </button>
            </div>
            <textarea
              value={reportMarkdown}
              readOnly
              rows={22}
              className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-mono text-sm resize-vertical"
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default function SocialMediaReportGenerator() {
  const { language } = useLanguage()
  const c = copy[language]

  const howToUse = (
    <div>
      <ol className="list-decimal list-inside space-y-1 ml-2">
        {c.howToUse.map((step, i) => (
          <li key={i}>
            <strong>{step.label}</strong> {step.text}
          </li>
        ))}
      </ol>
    </div>
  )

  return (
    <ToolAccessGate
      toolSlug="social-media-report-generator"
      toolName={c.toolName}
      toolDescription={c.toolDescription}
      howToUse={howToUse}
    >
      <SocialMediaReportGeneratorContent />
    </ToolAccessGate>
  )
}

function MetricInput(props: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div>
      <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">{props.label}</label>
      <input
        inputMode="numeric"
        value={props.value}
        onChange={(e) => props.onChange(e.target.value)}
        placeholder="0"
        className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder:text-gray-500 dark:placeholder:text-gray-400"
      />
    </div>
  )
}
